name: Generate Snake Animation

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  # Use the token from GitHub secrets for authentication

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # GitHub username for fetching contributions
          outputs: |
            dist/github-snake.svg  # Output path for the snake SVG file

      - name: Commit and push generated files to output branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Generated snake animation'
          add: 'dist/*'  # Commit all files from the dist directory
          branch: output  # Push to the output branch
          token: ${{ secrets.GH_TOKEN }}  # Authenticate using the token stored in GitHub secrets
